/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as PrivateRouteRouteImport } from "./routes/_private/route";
import { Route as PrivateIndexRouteImport } from "./routes/_private/index";
import { Route as PublicAuthRouteImport } from "./routes/_public/auth";
import { Route as PrivateProjectsRouteImport } from "./routes/_private/projects";
import { Route as PrivatePProjectSlugRouteImport } from "./routes/_private/p/$projectSlug";

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: "/_private",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PrivateRouteRoute,
} as any);
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: "/_public/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateProjectsRoute = PrivateProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => PrivateRouteRoute,
} as any);
const PrivatePProjectSlugRoute = PrivatePProjectSlugRouteImport.update({
  id: "/p/$projectSlug",
  path: "/p/$projectSlug",
  getParentRoute: () => PrivateRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof PrivateIndexRoute;
  "/projects": typeof PrivateProjectsRoute;
  "/auth": typeof PublicAuthRoute;
  "/p/$projectSlug": typeof PrivatePProjectSlugRoute;
}
export interface FileRoutesByTo {
  "/projects": typeof PrivateProjectsRoute;
  "/auth": typeof PublicAuthRoute;
  "/": typeof PrivateIndexRoute;
  "/p/$projectSlug": typeof PrivatePProjectSlugRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_private": typeof PrivateRouteRouteWithChildren;
  "/_private/projects": typeof PrivateProjectsRoute;
  "/_public/auth": typeof PublicAuthRoute;
  "/_private/": typeof PrivateIndexRoute;
  "/_private/p/$projectSlug": typeof PrivatePProjectSlugRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/projects" | "/auth" | "/p/$projectSlug";
  fileRoutesByTo: FileRoutesByTo;
  to: "/projects" | "/auth" | "/" | "/p/$projectSlug";
  id:
    | "__root__"
    | "/_private"
    | "/_private/projects"
    | "/_public/auth"
    | "/_private/"
    | "/_private/p/$projectSlug";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren;
  PublicAuthRoute: typeof PublicAuthRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_private": {
      id: "/_private";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof PrivateRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_private/": {
      id: "/_private/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof PrivateIndexRouteImport;
      parentRoute: typeof PrivateRouteRoute;
    };
    "/_public/auth": {
      id: "/_public/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof PublicAuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_private/projects": {
      id: "/_private/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof PrivateProjectsRouteImport;
      parentRoute: typeof PrivateRouteRoute;
    };
    "/_private/p/$projectSlug": {
      id: "/_private/p/$projectSlug";
      path: "/p/$projectSlug";
      fullPath: "/p/$projectSlug";
      preLoaderRoute: typeof PrivatePProjectSlugRouteImport;
      parentRoute: typeof PrivateRouteRoute;
    };
  }
}

interface PrivateRouteRouteChildren {
  PrivateProjectsRoute: typeof PrivateProjectsRoute;
  PrivateIndexRoute: typeof PrivateIndexRoute;
  PrivatePProjectSlugRoute: typeof PrivatePProjectSlugRoute;
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateProjectsRoute: PrivateProjectsRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivatePProjectSlugRoute: PrivatePProjectSlugRoute,
};

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicAuthRoute: PublicAuthRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
