/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as PrivateRouteRouteImport } from "./routes/_private/route";
import { Route as PrivateIndexRouteImport } from "./routes/_private/index";
import { Route as PublicAuthRouteImport } from "./routes/_public/auth";
import { Route as PrivateFlagsIndexRouteImport } from "./routes/_private/flags/index";

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: "/_private",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PrivateRouteRoute,
} as any);
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: "/_public/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateFlagsIndexRoute = PrivateFlagsIndexRouteImport.update({
  id: "/flags/",
  path: "/flags/",
  getParentRoute: () => PrivateRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof PrivateIndexRoute;
  "/auth": typeof PublicAuthRoute;
  "/flags/": typeof PrivateFlagsIndexRoute;
}
export interface FileRoutesByTo {
  "/auth": typeof PublicAuthRoute;
  "/": typeof PrivateIndexRoute;
  "/flags": typeof PrivateFlagsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_private": typeof PrivateRouteRouteWithChildren;
  "/_public/auth": typeof PublicAuthRoute;
  "/_private/": typeof PrivateIndexRoute;
  "/_private/flags/": typeof PrivateFlagsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/auth" | "/flags/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/auth" | "/" | "/flags";
  id:
    | "__root__"
    | "/_private"
    | "/_public/auth"
    | "/_private/"
    | "/_private/flags/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren;
  PublicAuthRoute: typeof PublicAuthRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_private": {
      id: "/_private";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof PrivateRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_private/": {
      id: "/_private/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof PrivateIndexRouteImport;
      parentRoute: typeof PrivateRouteRoute;
    };
    "/_public/auth": {
      id: "/_public/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof PublicAuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_private/flags/": {
      id: "/_private/flags/";
      path: "/flags";
      fullPath: "/flags/";
      preLoaderRoute: typeof PrivateFlagsIndexRouteImport;
      parentRoute: typeof PrivateRouteRoute;
    };
  }
}

interface PrivateRouteRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute;
  PrivateFlagsIndexRoute: typeof PrivateFlagsIndexRoute;
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateFlagsIndexRoute: PrivateFlagsIndexRoute,
};

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicAuthRoute: PublicAuthRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
